# Generated by Django 4.2.8 on 2024-01-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_target_is_achieved_alter_task_date_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
